### PR TITLE
Use higher level eZSys::serverProtocol() function

### PR DESCRIPTION
**Pull request by guillaumelecerf**

### CODE REVIEW

**Comment by guillaumelecerf** [comment]
Thanks.

**Comment by pkamps** [comment]
Thank you! Do you know that you need to server part in order to run the
mugo_dam extension?

On Wed, Sep 23, 2015 at 11:24 AM, Guillaume Lecerf <notifications@github.com

**Comment by guillaumelecerf** [comment]
I haven't tested it at all, but when reading the code, it is obvious that it needs a server ;)
Do you plan to opensource the server's code ?

**Comment by pkamps** [comment]
I'm happy to share it but it's a bit ugly, so I don't plan to publish it to
the public. But I send the code to people when they ask about it.

On Wed, Sep 23, 2015 at 11:30 AM, Guillaume Lecerf <notifications@github.com

**Comment by guillaumelecerf** [comment]
We have the exact same problematic here: sharing the images stored in the var/ezdfs between different environments (dev vs prod vs staging), so we'll give it a try.
We will keep you informed of our tests.

Thanks for your work !

**Comment by pkamps** [comment]
Let me know if you want me to send you the server code - not sure if I have
your email.

On Wed, Sep 23, 2015 at 11:39 AM, Guillaume Lecerf <notifications@github.com

**Pull request merged**
